version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/balashVI/go_circleci_2_test

    steps:
      - checkout

      - run:
          name: Run tests
          command: go test ./app/...
