version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.8
      
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

    working_directory: /go/src/github.com/balashVI/go_circleci_2_test

    steps:
      - checkout

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run: 
          name: Install GoVendor
          command: go get -u github.com/kardianos/govendor

      - restore_cache:
          key: m2-{{ checksum  "vendor/vendor.json" }}

      - run:
          name: Get dependencies
          command: govendor sync

      - save_cache:
          paths:
              - vendor/
          key: m2-{{ checksum  "vendor/vendor.json" }}

      - run:
          name: Run tests
          command: go test ./app/...

workflows:
  version: 2
  test:
    jobs:
     - test