version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.8
      
    working_directory: /go/src/github.com/balashVI/go_circleci_2_test

    steps:
      - checkout

      - run: 
          name: Install GoVendor
          command: go get -u github.com/kardianos/govendor

      - restore_cache:
          key: m2-{{ checksum  "vendor/vendor.json" }}

      - run:
          name: Get dependencies
          command: govendor sync -v

      - save_cache:
          paths:
              - vendor/
          key: m2-{{ checksum  "vendor/vendor.json" }}

      - run:
          name: Run tests
          command: go test ./app/...

  j1:
    docker:
      - image: circleci/golang:1.8
      
    working_directory: /go/src/github.com/balashVI/go_circleci_2_test

    steps:
      - run: echo "j1"

  j2:
    docker:
      - image: circleci/golang:1.8
      
    working_directory: /go/src/github.com/balashVI/go_circleci_2_test

    steps:
      - run: echo "j2"

workflows:
  version: 2
  test:
    jobs:
      - test
      - j2
      